# marketplace-fullstack/docker-compose.yml

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - marketplace-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: marketplace-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - marketplace-network

  # pgAdmin (interface web para PostgreSQL) - OPCIONAL
  pgadmin:
    image: dpage/pgadmin4
    container_name: marketplace-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@marketplace.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - marketplace-network

volumes:
  postgres_data:
  redis_data:

networks:
  marketplace-network:
    driver: bridge